//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/platooning/messages/Gap.msg.
//

#ifndef __GAP_M_H
#define __GAP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>veins/modules/application/platooning/messages/Gap.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Gap extends ManeuverMessage
 * {
 *     double distance;
 * }
 * </pre>
 */
class Gap : public ::ManeuverMessage
{
  protected:
    double distance;

  private:
    void copy(const Gap& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Gap&);

  public:
    Gap(const char *name=nullptr, short kind=0);
    Gap(const Gap& other);
    virtual ~Gap();
    Gap& operator=(const Gap& other);
    virtual Gap *dup() const override {return new Gap(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getDistance() const;
    virtual void setDistance(double distance);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Gap& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Gap& obj) {obj.parsimUnpack(b);}


#endif // ifndef __GAP_M_H

