//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/platooning/messages/LaneAck.msg.
//

#ifndef __LANEACK_M_H
#define __LANEACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>veins/modules/application/platooning/messages/LaneAck.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet LaneAck extends ManeuverMessage
 * {
 * }
 * </pre>
 */
class LaneAck : public ::ManeuverMessage
{
  protected:

  private:
    void copy(const LaneAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LaneAck&);

  public:
    LaneAck(const char *name=nullptr, short kind=0);
    LaneAck(const LaneAck& other);
    virtual ~LaneAck();
    LaneAck& operator=(const LaneAck& other);
    virtual LaneAck *dup() const override {return new LaneAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LaneAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LaneAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __LANEACK_M_H

