//
// Generated file, do not edit! Created by nedtool 5.5 from plexe/messages/DissolveAck.msg.
//

#ifndef __DISSOLVEACK_M_H
#define __DISSOLVEACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/DissolveAck.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet DissolveAck extends ManeuverMessage
 * {
 * }
 * </pre>
 */
class PLEXE_API DissolveAck : public ::ManeuverMessage
{
  protected:

  private:
    void copy(const DissolveAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DissolveAck&);

  public:
    DissolveAck(const char *name=nullptr, short kind=0);
    DissolveAck(const DissolveAck& other);
    virtual ~DissolveAck();
    DissolveAck& operator=(const DissolveAck& other);
    virtual DissolveAck *dup() const override {return new DissolveAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DissolveAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DissolveAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DISSOLVEACK_M_H

