//
// Generated file, do not edit! Created by nedtool 5.5 from plexe/messages/GapAck.msg.
//

#ifndef __GAPACK_M_H
#define __GAPACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/GapAck.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet GapAck extends ManeuverMessage
 * {
 *     double platoonSpeed;
 *     int platoonLane;
 * }
 * </pre>
 */
class PLEXE_API GapAck : public ::ManeuverMessage
{
  protected:
    double platoonSpeed;
    int platoonLane;

  private:
    void copy(const GapAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GapAck&);

  public:
    GapAck(const char *name=nullptr, short kind=0);
    GapAck(const GapAck& other);
    virtual ~GapAck();
    GapAck& operator=(const GapAck& other);
    virtual GapAck *dup() const override {return new GapAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getPlatoonSpeed() const;
    virtual void setPlatoonSpeed(double platoonSpeed);
    virtual int getPlatoonLane() const;
    virtual void setPlatoonLane(int platoonLane);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GapAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GapAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __GAPACK_M_H

