//
// Generated file, do not edit! Created by nedtool 5.5 from plexe/messages/InterferingBeacon.msg.
//

#ifndef __INTERFERINGBEACON_M_H
#define __INTERFERINGBEACON_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



/**
 * Class generated from <tt>plexe/messages/InterferingBeacon.msg:21</tt> by nedtool.
 * <pre>
 * packet InterferingBeacon
 * {
 * }
 * </pre>
 */
class PLEXE_API InterferingBeacon : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const InterferingBeacon& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InterferingBeacon&);

  public:
    InterferingBeacon(const char *name=nullptr, short kind=0);
    InterferingBeacon(const InterferingBeacon& other);
    virtual ~InterferingBeacon();
    InterferingBeacon& operator=(const InterferingBeacon& other);
    virtual InterferingBeacon *dup() const override {return new InterferingBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const InterferingBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, InterferingBeacon& obj) {obj.parsimUnpack(b);}


#endif // ifndef __INTERFERINGBEACON_M_H

