//
// Generated file, do not edit! Created by nedtool 5.5 from plexe/messages/JoinPlatoonRequest.msg.
//

#ifndef __JOINPLATOONREQUEST_M_H
#define __JOINPLATOONREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/JoinPlatoonRequest.msg:30</tt> by nedtool.
 * <pre>
 * // Request to join a Platoon.
 * // Is sent from a possible joiner to the leader of the Platoon.
 * packet JoinPlatoonRequest extends ManeuverMessage
 * {
 *     // the id of the lane the joiner currently drives on
 *     int currentLaneIndex;
 *     double xPos;
 *     double yPos;
 * }
 * </pre>
 */
class PLEXE_API JoinPlatoonRequest : public ::ManeuverMessage
{
  protected:
    int currentLaneIndex;
    double xPos;
    double yPos;

  private:
    void copy(const JoinPlatoonRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const JoinPlatoonRequest&);

  public:
    JoinPlatoonRequest(const char *name=nullptr, short kind=0);
    JoinPlatoonRequest(const JoinPlatoonRequest& other);
    virtual ~JoinPlatoonRequest();
    JoinPlatoonRequest& operator=(const JoinPlatoonRequest& other);
    virtual JoinPlatoonRequest *dup() const override {return new JoinPlatoonRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getCurrentLaneIndex() const;
    virtual void setCurrentLaneIndex(int currentLaneIndex);
    virtual double getXPos() const;
    virtual void setXPos(double xPos);
    virtual double getYPos() const;
    virtual void setYPos(double yPos);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const JoinPlatoonRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, JoinPlatoonRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __JOINPLATOONREQUEST_M_H

