//
// Generated file, do not edit! Created by nedtool 5.5 from plexe/messages/LeaveAck.msg.
//

#ifndef __LEAVEACK_M_H
#define __LEAVEACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef PLEXE_API
#  if defined(PLEXE_EXPORT)
#    define PLEXE_API  OPP_DLLEXPORT
#  elif defined(PLEXE_IMPORT)
#    define PLEXE_API  OPP_DLLIMPORT
#  else
#    define PLEXE_API
#  endif
#endif



// cplusplus {{
#include "ManeuverMessage_m.h"
// }}

/**
 * Class generated from <tt>plexe/messages/LeaveAck.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet LeaveAck extends ManeuverMessage
 * {
 *     int currentLaneIndex;
 *     int frontId;
 * }
 * </pre>
 */
class PLEXE_API LeaveAck : public ::ManeuverMessage
{
  protected:
    int currentLaneIndex;
    int frontId;

  private:
    void copy(const LeaveAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LeaveAck&);

  public:
    LeaveAck(const char *name=nullptr, short kind=0);
    LeaveAck(const LeaveAck& other);
    virtual ~LeaveAck();
    LeaveAck& operator=(const LeaveAck& other);
    virtual LeaveAck *dup() const override {return new LeaveAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getCurrentLaneIndex() const;
    virtual void setCurrentLaneIndex(int currentLaneIndex);
    virtual int getFrontId() const;
    virtual void setFrontId(int frontId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LeaveAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LeaveAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __LEAVEACK_M_H

